security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
#            guard:
#                authenticators:
#                    - App\Security\LoginFormAuthenticator
            form_login:
                # "app_login" is the name of the route created previously
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, role: ROLE_ADMIN }
        - { path: ^/category/hierarchy, role: ROLE_USER }
        - { path: ^/category/, role: ROLE_ADMIN }
        - { path: ^/anchor/list, role: ROLE_USER }
        - { path: ^/anchor/, role: ROLE_ADMIN }
        - { path: ^/trail/new, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/trail/, role: ROLE_USER }
        - { path: ^/message/send, role: ROLE_USER }
        - { path: ^/message, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY } #unprotect dev-toolbar so to redirect to right page.
        - { path: ^/main, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
