emfox_gps_index:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
        path: /main/google
        permanent: true
emfox_gps_main:
    path:     /main/{maptype}
    defaults:
        _controller: "App\\Controller\\DefaultController::main"
        maptype: "google"
