controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
emfox_gps_index:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
        path: /main/tianditu
        permanent: true
emfox_gps_main:
    path:     /main/{maptype}
    defaults:
        _controller: "App\\Controller\\DefaultController::main"
        maptype: "tianditu"
    requirements:
        maptype: 'google|baidu|tianditu'

